### Request sms auth code
POST {{host}}/api/auth/request
Content-Type: application/json

{
  "name": "Smith",
  "phone_code": "1",
  "phone_number": "5551234568"
}


### Verify user's auth code
POST {{host}}/api/auth/verify
Content-Type: application/json

{
  "code": "575567",
  "phone_code": "1",
  "phone_number": "5551234568"
}


###
GET {{host}}/api/me
Authorization: Bearer {{access_token}}
